// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcppLinNest
int rcppLinNest(NumericMatrix X, NumericVector y, NumericVector w, NumericVector adaweights, int nrow, int ncol, int numGroup, IntegerVector rangeGroupInd, IntegerVector groupLen, NumericVector lambda, int step, NumericMatrix beta, int innerIter, int outerIter, double thresh, double outerThresh, NumericVector eta, double gamma, IntegerVector betaIsZero, double momentum, int reset);
RcppExport SEXP lagr_rcppLinNest(SEXP XSEXP, SEXP ySEXP, SEXP wSEXP, SEXP adaweightsSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP numGroupSEXP, SEXP rangeGroupIndSEXP, SEXP groupLenSEXP, SEXP lambdaSEXP, SEXP stepSEXP, SEXP betaSEXP, SEXP innerIterSEXP, SEXP outerIterSEXP, SEXP threshSEXP, SEXP outerThreshSEXP, SEXP etaSEXP, SEXP gammaSEXP, SEXP betaIsZeroSEXP, SEXP momentumSEXP, SEXP resetSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type adaweights(adaweightsSEXP );
        Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP );
        Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP );
        Rcpp::traits::input_parameter< int >::type numGroup(numGroupSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type rangeGroupInd(rangeGroupIndSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type groupLen(groupLenSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP );
        Rcpp::traits::input_parameter< int >::type step(stepSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type beta(betaSEXP );
        Rcpp::traits::input_parameter< int >::type innerIter(innerIterSEXP );
        Rcpp::traits::input_parameter< int >::type outerIter(outerIterSEXP );
        Rcpp::traits::input_parameter< double >::type thresh(threshSEXP );
        Rcpp::traits::input_parameter< double >::type outerThresh(outerThreshSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP );
        Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type betaIsZero(betaIsZeroSEXP );
        Rcpp::traits::input_parameter< double >::type momentum(momentumSEXP );
        Rcpp::traits::input_parameter< int >::type reset(resetSEXP );
        int __result = rcppLinNest(X, y, w, adaweights, nrow, ncol, numGroup, rangeGroupInd, groupLen, lambda, step, beta, innerIter, outerIter, thresh, outerThresh, eta, gamma, betaIsZero, momentum, reset);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
