# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppLinNest <- function(X, y, w, adaweights, nrow, ncol, numGroup, rangeGroupInd, groupLen, lambda, step, beta, innerIter, outerIter, thresh, outerThresh, eta, gamma, betaIsZero, momentum, reset) {
    .Call('lagr_rcppLinNest', PACKAGE = 'lagr', X, y, w, adaweights, nrow, ncol, numGroup, rangeGroupInd, groupLen, lambda, step, beta, innerIter, outerIter, thresh, outerThresh, eta, gamma, betaIsZero, momentum, reset)
}

