# This file was generated by attributes::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

killTest <- function(ll, x) {
    .Call('lagr_killTest', PACKAGE = 'lagr', ll, x)
}

rcppLinNest <- function(X, y, w, adaweights, linkinv, devfun, nrow, ncol, numGroup, rangeGroupInd, groupLen, lambda, beta, innerIter, outerIter, thresh, outerThresh, eta, gamma, betaIsZero, reset) {
    .Call('lagr_rcppLinNest', PACKAGE = 'lagr', X, y, w, adaweights, linkinv, devfun, nrow, ncol, numGroup, rangeGroupInd, groupLen, lambda, beta, innerIter, outerIter, thresh, outerThresh, eta, gamma, betaIsZero, reset)
}
